---
name: bosh-dns

update:
  canaries: 2
  canary_watch_time: 1000-60000
  max_in_flight: 5
  serial: false
  update_watch_time: 1000-60000

instance_groups:
- name: bosh-dns
  azs: [z1]
  instances: 2
  vm_type: large
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: needs-alias
    release: dns-acceptance
  - name: bosh-dns-windows
    release: bosh-dns
    properties:
      address: 0.0.0.0
      api:
        server:
          tls: ((dns_api_server_tls))
        client:
          tls: ((dns_api_client_tls))
      recursors: ["10.0.16.191:9955"]
      cache:
        enabled: true
      aliases:
        asterisk.alias: ["*.*-dns.default.bosh-dns.bosh."]
        another.asterisk.alias: ["*.bosh-dns*.default.bosh-dns.bosh."]
        yetanother.asterisk.alias: ["*.*.default.bosh-dns.bosh."]
  - name: windows-firewall-rules
    release: dns-acceptance
  - name: configures-handler
    release: dns-acceptance
    properties:
      handler_server_address: 10.0.16.191:9956
      handler_domain: handler.internal.local.

releases:
- name: bosh-dns
  version: latest
- name: dns-acceptance
  version: latest

stemcells:
- alias: default
  os: ((base_stemcell))
  version: latest

variables:
- name: dns_api_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-api-tls-ca

- name: dns_api_server_tls
  type: certificate
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
      - server_auth

- name: dns_api_client_tls
  type: certificate
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
