---
name: bosh-dns-shared-acceptance

update:
  canaries: 5
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000

instance_groups:
- name: acceptance-tests
  azs: [z1]
  instances: 1
  vm_type: large
  stemcell: default
  lifecycle: errand
  networks:
  - name: private
    static_ips: [10.0.16.191]
  jobs:
  - name: acceptance-tests
    release: bosh-dns
    properties:
      bosh_ca_cert: ((bosh_ca_cert))
      bosh_client_secret: ((bosh_client_secret))
      bosh_client: ((bosh_client))
      bosh_environment: ((bosh_environment))
      bosh_deployment: ((bosh_deployment))
      base_stemcell: ((base_stemcell))

releases:
- name: bosh-dns
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
