---
name: ((deployment_name))

update:
  canaries: 5
  canary_watch_time: 30000-120000
  max_in_flight: 5
  serial: false
  update_watch_time: 30000-120000

instance_groups:
- name: acceptance-tests-windows
  azs: [z1]
  instances: 1
  vm_type: large
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: default
  networks:
  - name: private
  jobs:
  - name: acceptance-tests-windows
    release: bosh-dns
  - name: bosh-dns-windows
    release: bosh-dns
    properties:
      api:
        server:
          tls: ((dns_api_server_tls))
        client:
          tls: ((dns_api_client_tls))

releases:
- name: bosh-dns
  version: latest

stemcells:
- alias: default
  os: ((windows_stemcell))
  version: latest

variables:
- name: dns_api_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-api-tls-ca

- name: dns_api_server_tls
  type: certificate
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
      - server_auth

- name: dns_api_client_tls
  type: certificate
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
